name: .NET

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 4.8.x
    - name: Restore dependencies
      run: dotnet restore ./src/IdeaStatiCa.Public.sln
    - name: Build
      run: dotnet build ./src/IdeaStatiCa.Public.sln --no-restore
    - name: Test
      run: dotnet test ./src/IdeaStatiCa.Public.sln --no-build --verbosity normal
