name: .NET build artifacts

on:
  workflow_dispatch:
    inputs:
      name:
        description: 'Person to greet'
        required: true
        default: 'Mona the Octocat'

jobs:
  BuildAndTest:
    name: "Build and Create IOM"
    runs-on: windows-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        path: main

    - name: Setup .NET
      uses: microsoft/setup-msbuild@v1

    - name: Setup nuget.exe
      uses: NuGet/setup-nuget@v1.0.5
      
    - name: Setup VSTest Path
      uses: darenm/Setup-VSTest@v1

    - name: Nuget restore dependencies
      run: nuget restore ./src/IdeaStatiCa.Public.sln
      working-directory: main

    - name: Build
      run: msbuild ./src/IdeaStatiCa.Public.sln /p:Configuration=Release
      working-directory: main

    - name: Create zip
      uses: edgarrc/action-7z@v1
      with:
        args: 7z a -t7z -mx=9 ./src/Examples/ConnHiddenCalc/ConnectionHiddenCalculation/bin/Release/ConnectionHiddenCalculation.7z ./src/Examples/ConnHiddenCalc/ConnectionHiddenCalculation/bin/Release/net48

    - name: 'Upload Artifact'
      uses: actions/upload-artifact@v2
      with:
        name: my-artifact
        path: ./src/Examples/ConnHiddenCalc/ConnectionHiddenCalculation/bin/Release/ConnectionHiddenCalculation.7z
        retention-days: 5
